### ISSUE TITLE
Grid Bot - Margin

### ISSUE THREAD

**Issue by timquinn** [tudorelu/pyjuque#10]
I see that you are working on a grid bot.  I've been looking for weeks for a grid that can work with Margin like the ones at Pionex do.  That would be a killer feature that I'd be happy to compensate for!

**Comment by tudorelu** [comment]
Hey Tim,

It would be a non-trivial endeavor to add margin functionality to the grid bot, but I won't say no if you want to hire me to do it! If you're interested you can reach me via email at tudor (dot) barbu7[at] gmail (dot) com
