### ISSUE TITLE
Error executing examples/try_order_management.py in feature branch / order_management

### ISSUE THREAD

**Issue by 4n71chr157** [tudorelu/pyjuque#2]
**Description**
When i am execute the python file examples/try_order_management.py in feature/order_management, 
i will get following error stack:

```
$ python examples/try_order_management.py 
Getting active pairs:
Traceback (most recent call last):
  File "examples/try_order_management.py", line 73, in <module>
    Main()
  File "examples/try_order_management.py", line 63, in Main
    execute_bot(
  File "E:\Develop\pyjuque\bot\Engine\OrderManagement.py", line 16, in execute_bot
    active_pairs = bot.getActivePairs(session)
AttributeError: 'NoneType' object has no attribute 'getActivePairs'
```

**System Information**
 - Windows 10 Professional
 - VS Code V1.48.1
 - Python 3.8.2

**Additional Info**
I think some values are not set in the database at this point, so it deliver a NoneType Error. I hope you can help me at this point to figure what the problem is in this case. 

Thank you very much!

**Comment by tudorelu** [comment]
Hey, thanks for submitting a first issue! Yes, first time you run it you must uncomment line 57 in try_order_management.py which initialises a database.

https://github.com/tudorelu/pyjuque/blob/feature/order_management/examples/try_order_management.py#L57

**Comment by tudorelu** [comment]
Hey, thanks for submitting a first issue! Yes, first time you run it you must uncomment line 57 in try_order_management.py which initialises a database.

https://github.com/tudorelu/pyjuque/blob/feature/order_management/examples/try_order_management.py#L57

**Comment by tudorelu** [comment]
Hey, thanks for submitting a first issue! Yes, first time you run it you must uncomment line 57 in try_order_management.py which initialises a database.

https://github.com/tudorelu/pyjuque/blob/feature/order_management/examples/try_order_management.py#L57
