### ISSUE TITLE
Cannot trade symbol without '/' in the name

### ISSUE THREAD

**Issue by revmischa** [tudorelu/pyjuque#22]
FTX has futures. They have symbols like `ETH-PERP`.

If I try to load up this symbol I get the error:
```
  File ".../lib/python3.9/site-packages/pyjuque/Bot.py", line 65, in defineBot
    quote_asset = symbols[0].split('/')[1]
IndexError: list index out of range
```

<img width="534" alt="Screenshot 2021-08-22 at 12 09 12" src="https://user-images.githubusercontent.com/245131/130349413-72c29ffb-b6d9-4f89-9278-e44d5312d8f5.png">

**Comment by tudorelu** [comment]
Hey there, I merged your [pull request](https://github.com/tudorelu/pyjuque/pull/24) about this issue. 
Also if you have added FTX integration feel free to make a pull request and I'll merge it.

Either way, thanks for using pyjuque.
