### ISSUE TITLE
Balance & Selling manually caused pyjuque notification messages non-stop

### ISSUE THREAD

**Issue by hlford** [tudorelu/pyjuque#29]
**Describe the bug**

I added more funds in the exchange but pyjuque didn't notice because it's still using the starting/current balance from the database instead letting me update the balance:
INFO:pyjuque.Engine.BotController:Error placing order
<class 'ccxt.base.errors.InsufficientFunds'>

I manually sold the coin on the market. But pyjuque didn't notice it and kept on trying to access the record in the database and notify about it. Is there any to get rid of the old/expired records in the database?
INFO:pyjuque.Engine.BotController:Error getting data from the exchange for updating open order

**Comment by tudorelu** [comment]
I know this is not ideal but right now the fix would be updating the bot's current_balance entry in the database manually. 

I'm currently doing some massive reworking to this library, changing the code base - so in the new code I will avoid this issue, but I'm not sure I will fix it in the current codebase (the one you're using now). If you have the time / will, free to make a pull request that fixes it and I will merge it. 

The fix would be as simple as checking that the balance on the exchange is greater than or equal to the bot's current balance. If it is, then good, but if not - update the bot's balance to be equal to the one displayed on the exchange.

**Comment by hlford** [comment]
I'm still learning python and the code is still quite solid.  Right now I just avoid selling manually. I'm trying to tweak the code to fix bot not updating the order/pair when it gets busy since there's no "self-cleanup" routine yet.  I'm moving strategies into the startup py to see if I can slow it down a bit so it has som breathing room to update order/pair after selling:

<class 'ccxt.base.errors.OrderNotFound'>
kucoin order not exist.
<traceback object at 0x7fb1eb4200>
INFO:pyjuque.Engine.BotController:Error getting data from the exchange for updating open order
