### ISSUE TITLE
Interest in using Pandas TA as a TA Library?

### ISSUE THREAD

**Issue by twopirllc** [tudorelu/pyjuque#5]
Hello @tudorelu,

I came across your Github account through another user and saw that you are creating an Algo Trading System and posting via YouTube. Awesome!

I noticed that you are using _pyti_ for TA but it seems to have gone stale nearly two years ago. I was wondering if you would be interested in trying and incorporating [Pandas TA](https://github.com/twopirllc/pandas-ta) into your project? It is built to be compatible with Pandas as an DataFrame extension, correlated with TA Lib (for common indicators), other popular indicators like TTM Squeeze and Trend, and much more! Also check out some [Examples](https://github.com/twopirllc/pandas-ta/tree/master/examples) for implementation and features.

Thanks for your time,
Kevin Johnson

**Comment by tudorelu** [comment]
Hi @twopirllc, this sounds interesting I'll have a look!

**Comment by twopirllc** [comment]
@tudorelu,

If you have any questions, let me know.

KJ

**Comment by tudorelu** [comment]
Definitely - just had a thought, wanted to see your take on it... you know with real time trading sometimes you want to compute an indicator value only for the last Candle for example - because you already computed it for the previous ones. How many indicators in your library would have that capability, or should most of them be rewritten to allow for that? (I imagine a lot of devs would like to have this ability in a TA library..)

**Comment by twopirllc** [comment]
@tudorelu,

Excellent question.

> I imagine a lot of devs would like to have this ability in a TA library..

No doubt!

Yet, in my experience of both creating indicators and reverse engineering them from [TA Lib](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/), Trading View, et al, it is not possible for many indicators.

In fact it was a discussion on my repo as well. It's the first Pinned Issue: [**How to utilize this Framework for live ticks** _#87_](https://github.com/twopirllc/pandas-ta/issues/87). Unfortunately, I haven't had much chance to personally address this issue more. Hopefully soon! 🤞 

## Brokers, Charting Software, and Web Platforms

Traditional Broker Platforms like Trade Station, Think or Swim, Interactive Brokers as well as  specialty charting platforms like MultiCharts, Sierra Charts et al are a mix of C, C++, C#, and Java typically. I have not found anything online yet on how any of them do it, but it's unlikely a concern considering their choice of language.

For the web trading platform Trading View, this is how they handle the [Execution of Pine Script](https://www.tradingview.com/pine-script-docs/en/v4/Quickstart_guide.html#execution-model-of-pine-scripts)

More specifically:
<img width="699" alt="Screen Shot 2020-09-06 at 9 05 07 AM" src="https://user-images.githubusercontent.com/18198392/92333600-b0502300-f03b-11ea-9884-1613392b8a12.png">

## Requirements or Limitations

I suppose it really depends on your requirements or limitations.

If the requirement is truly HFT, microseconds trading with a dedicated machine as close to the exchange as possible, then Python is obviously not the choice. However if it is tick data, then you should be fine in many cases with performant hardware. Lastly for 1 minute and higher time frames, I wouldn't be concerned.

For instance, I am running a 2013 Mac Book Pro with 4G RAM, 4 Cores. When using **Pandas TA**, I can process over a hundred different indicators in about 4secs with ohlcv data containing 700 rows. However in reality, one would have a small sample of indicators to use and it takes my machine microseconds.

For example, when I used this subset of indicators (max period of 200) with 700 bars I got around 50 ms (or 0.05 secs) to process them. When I take 210 bars, 10 extra bars for buffer, I get around 30 ms (or 0.03 secs). Even with my hardware limitation, TA speed bottlenecks are trivial.

<img width="585" alt="Screen Shot 2020-09-06 at 9 24 35 AM" src="https://user-images.githubusercontent.com/18198392/92336172-9ff77280-f052-11ea-9048-c39ccce67bac.png">

But if you have a small portfolio to live track and calculate as a scanner list, of course it may take marginally longer to process them in a blocking manner.

> How many indicators in your library would have that capability, or should most of them be rewritten to allow for that?

So in my opinion, I don't think it is necessary to rewrite the few that may benefit. Even with older hardware, TA is pretty fast.

Apologies if this was overkill...
KJ

**Comment by tudorelu** [comment]
Definitely not an overkill, really thanks for the detailed explanation. It
put me at ease with respect to the speed of calculation / perceived
bottleneck as I haven't tested their speed myself.

I imagine that a well thought out algorithm can perform without issues in
the current scenario, with a small number of pairs - however you're right,
if you want to compute hundreds of indicators on dozens of pairs every
minute - it will take longer than a minute :P so rewriting some of them in
a recursive fashion to compute 'in real time' - at least for the indicators
that it is possible - might be a use case for python, slightly different
than the HFT algo which I totally agree that python wouldn't be the
language for.

Again thanks for this answer and your effort of converting TA-lib to python
- I am almost certainly using this library for pyjuque as I wanted to
change pyti for a long time - I might even give it a try to update some
indicators to real-time!

**Comment by twopirllc** [comment]
@tudorelu,

> Definitely not an overkill, really thanks for the detailed explanation. It
put me at ease with respect to the speed of calculation / perceived
bottleneck as I haven't tested their speed myself.

Cool.

> So rewriting some of them in a recursive fashion to compute 'in real time' - at least for the indicators that it is possible - might be a use case for python

Yeah.

> I imagine that a well thought out algorithm can perform without issues in
the current scenario, with a small number of pairs - however you're right,
if you want to compute hundreds of indicators on dozens of pairs every
minute

Right. I am also building out a [Watchlist Class](https://github.com/twopirllc/pandas-ta/blob/master/examples/watchlist.py) that manages a group of tickers and fetches data from AlphaVantage (currently), and processes TA assigned to it. It's a _work in progress_ with the goal to add more data sources, brokers, and an event loop for live or simulation.

> Again thanks for this answer and your effort of converting TA-lib to python
- I am almost certainly using this library for pyjuque as I wanted to
change pyti for a long time - I might even give it a try to update some
indicators to real-time!

Thanks! Yeah, _TA Lib_ also does not easily install some systems. So I made Pandas TA to have the same level of accuracy as _TA Lib_, ease of use, and compatibility with the Python Data Science / ML / FinTech ecosystem. I have other cool features in mind to add. I just need to make time to program them. Looking forward to what you produce.

Thanks,
KJ

**Comment by TekpreXyz** [comment]
hi all nice guy!
do you know this project?
https://github.com/freqtrade/freqtrade
Maybe you can take some ispiration from.

**Comment by TekpreXyz** [comment]
another interesting source is 👍
https://towardsdatascience.com/how-to-create-a-fully-automated-ai-based-trading-system-with-python-708503c1a907
https://www.freqtrade.io/en/latest/strategy-customization/
https://github.com/ccxt/ccxt
https://www.shrimpy.io/demo

**Comment by TekpreXyz** [comment]
import ccxt
from datetime import datetime
import plotly.graph_objects as go
# collect the candlestick data from Binance
binance = ccxt.binance()
trading_pair = 'LTC/BTC'
candles = binance.fetch_ohlcv(trading_pair, '1h')
dates = []
open_data = []
high_data = []
low_data = []
close_data = []
# format the data to match the charting library
for candle in candles:
    dates.append(datetime.fromtimestamp(candle[0] / 1000.0).strftime('%Y-%m-%d %H:%M:%S.%f'))
    open_data.append(candle[1])
    high_data.append(candle[2])
    low_data.append(candle[3])
    close_data.append(candle[4])
# plot the candlesticks
fig = go.Figure(data=[go.Candlestick(x=dates,
                       open=open_data, high=high_data,
                       low=low_data, close=close_data)])
fig.show()

**Comment by TekpreXyz** [comment]
https://medium.com/coinmonks/python-scripts-for-ccxt-crypto-candlestick-ohlcv-charting-data-83926fa16a13

**Comment by TekpreXyz** [comment]
#this is for using dash for preview 
import ccxt
from datetime import datetime
import plotly.graph_objects as go
import dash
import dash_core_components as dcc
import dash_html_components as html


# collect the candlestick data from Binance
binance = ccxt.binance()
trading_pair = 'BTC/USDT'
candles = binance.fetch_ohlcv(trading_pair, '1m')
dates = []
open_data = []
high_data = []
low_data = []
close_data = []
# format the data to match the charting library
for candle in candles:
    dates.append(datetime.fromtimestamp(candle[0] / 1000.0).strftime('%Y-%m-%d %H:%M:%S.%f'))
    open_data.append(candle[1])
    high_data.append(candle[2])
    low_data.append(candle[3])
    close_data.append(candle[4])
# plot the candlesticks
fig = go.Figure(data=[go.Candlestick(x=dates,
                       open=open_data, high=high_data,
                       low=low_data, close=close_data)])

app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig),
    dcc.Interval(
            id='interval-component',
            interval=1*1000, # in milliseconds
            n_intervals=0
        )
])
app.run_server(debug=True, use_reloader=True)
fig.show()

**Comment by TekpreXyz** [comment]
`import ccxt
from datetime import datetime
import plotly.graph_objects as go
import dash
import dash_core_components as dcc
import dash_html_components as html


# collect the candlestick data from Binance
binance = ccxt.binance()
trading_pair = 'BTC/USDT'
candles = binance.fetch_ohlcv(trading_pair, '1m')
dates = []
open_data = []
high_data = []
low_data = []
close_data = []
# format the data to match the charting library
for candle in candles:
    dates.append(datetime.fromtimestamp(candle[0] / 1000.0).strftime('%Y-%m-%d %H:%M:%S.%f'))
    open_data.append(candle[1])
    high_data.append(candle[2])
    low_data.append(candle[3])
    close_data.append(candle[4])
# plot the candlesticks
fig = go.Figure(data=[go.Candlestick(x=dates,
                       open=open_data, high=high_data,
                       low=low_data, close=close_data)])

app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig),
    dcc.Interval(
            id='interval-component',
            interval=1*1000, # in milliseconds
            n_intervals=0
        )
])
app.run_server(debug=True, use_reloader=True)
fig.show()
`
